version: '3.8'

services:
  ingestor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DEBUG=False
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=documents
      - QDRANT_PREFER_GRPC=True
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - EMBEDDING_BATCH_SIZE=32
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200
    depends_on:
      - qdrant
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
    restart: unless-stopped

volumes:
  qdrant-data: 